name: biobb_wf_flexdyn
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.9
  - biobb_flexdyn==4.1.0
  - biobb_flexserv==4.1.0
  - biobb_io==4.1.0
  - biobb_structure_utils==4.1.0
  - biobb_gromacs==4.1.0
  - biobb_analysis==4.1.0
  - jupyter
  - plotly
  - nglview
  - simpletraj
  - pandas
