name: biobb_wf_flexdyn
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.8
  - biobb_flexdyn==4.1.0
  - biobb_flexserv==4.1.0
  - biobb_io==4.1.0
  - biobb_structure_utils==4.1.0
  - biobb_gromacs==4.1.0
  - biobb_analysis==4.1.0
  - jupyter_client==7.3.2
  - ipywidgets==7.6.6
  #- traitlets==5.9.0
  - plotly
  - nglview
  - simpletraj
  - pandas